import { Metadata } from "next";
import SignInForm from "./_component/SignInForm";

export const metadata: Metadata = {
    title: "Sign In",
    description: "Generated by create next app",
};

export default function SignInPage() {
    return <SignInForm />;
}
