name: FE CI/CD

on:
  push:
    branches: 
      - main

env:
  IMAGE_NAME: ghcr.io/khtnk22-datn-ba-copilot/frontend:latest

jobs:
  # ========== CI: Build & Push ==========
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ secrets.ACTOR }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME

  # ========== CD: Deploy ==========
  deploy:
    runs-on: ["self-hosted", "Linux", "X64"]
    needs: build_and_publish

    steps:
      - name: Login to GHCR (server)
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.ACTOR }} --password-stdin

      - name: Pull latest image
        run: docker pull $IMAGE_NAME

      - name: Restart container
        run: docker compose up -d frontend
        working-directory: /home/bacopilot/bacopilot

      - name: Cleanup old images
        run: docker image prune -f
